import React from "react";
import { useLoader } from "react-three-fiber";
import * as THREE from "three";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import model from "./deerhead.glb?url";

interface DeerheadProps {
  layer: number;
  material: THREE.Material;
}

// Component auto-generated by GLTFJSX: https://github.com/react-spring/gltfjsx
export function Deerhead({ layer, material }: DeerheadProps) {
  const gltf = useLoader(GLTFLoader, model);
  const mesh = gltf.nodes.mesh_0 as THREE.Mesh;

  return (
    <group rotation={[-1.8, 0, -1.2]} position={[0, -7, 0]}>
      <mesh
        geometry={mesh.geometry}
        material={material}
        layers={[layer]}
        receiveShadow
        castShadow
      />
    </group>
  );
}
